import {
  LayoutDashboard,
  UploadCloud,
  Bell,
  Settings,
  BookMarked,
  Wand2,
  ServerCog,
  UserPlus,
  SlidersHorizontal,
  LifeBuoy,
  Files,
  ClipboardList,
  History,
  Building2,
  Users,
  Library,
  BarChart3,
  FolderKanban,
  GitBranch,
  CalendarClock,
  CalendarRange,
  CreditCard,
  GraduationCap,
  ScrollText,
  UserCog,
  type LucideIcon,
} from "lucide-react";

const ICONS: Record<string, LucideIcon> = {
  LayoutDashboard,
  UploadCloud,
  Bell,
  Settings,
  BookMarked,
  Wand2,
  ServerCog,
  UserPlus,
  SlidersHorizontal,
  LifeBuoy,
  Files,
  ClipboardList,
  History,
  Building2,
  Users,
  Library,
  BarChart3,
  FolderKanban,
  GitBranch,
  CalendarClock,
  CalendarRange,
  CreditCard,
  GraduationCap,
  ScrollText,
  UserCog,
};

export function NavIcon({ name, className }: { name: string; className?: string }) {
  const Icon = ICONS[name] ?? LayoutDashboard;
  return <Icon className={className} />;
}
